### ISSUE TITLE
Scroll bar bugs out after moving the Overview tab around

### ISSUE THREAD

**Issue by wbSD** [peterhaneve/evemon#115]
This was part of the description of #110 but it seems to happen for another reason.

I was able to identify the weird client size as the cause of the minimize/maximize scenario, but I haven't nailed what's the cause of this other one.
For whatever reason it is, the PerformCustomLayout method is called _**12 times**_ when moving the overview tab. It happens in groups of 3 - once with no controls in it and then 2 with controls (actually running the calculations).
The last (and only that one) messes up the vertical scroll bar maximum range (inspect VerticalScroll.Maximum after the foreach that runs overviewItem.SetBounds)

In order to reproduce it you need a large amount of characters (I have 19).
Then you drag the overview tab from being the first tab to being another one.
In this example I just move it to the second tab. I've seen the same thing happen when accidentally holding down the mouse button for a bit too long when trying to click the overview when it's on the top row of tabs (in the back).
![image](https://user-images.githubusercontent.com/1277455/48510761-15c69480-e855-11e8-8cbb-3f0f8767396e.png)

As you can see on this screenshot there is an odd number of characters, and scrolling to the bottom shows an empty slot.
After dragging the Overview tab it looks like this:
![image](https://user-images.githubusercontent.com/1277455/48510955-96859080-e855-11e8-8df9-77bab9fb4577.png)

As you can see the scroll bar is at the bottom, but the view isn't actually scrolled down to the last character.

As mentioned on pull request #111 the suggested change completely removes the problem with the scrollbar.
It doesn't change the fact that the method is called so often, though.

**Comment by peterhaneve** [comment]
PerformCustomLayout is called every time the control is resized or made visible / invisible. One invocation comes from the MonitoredCharacterCollectionChanged event which is called implicitly by the tab drag/drop handler. Since the character list order might have actually changed, this call is probably more difficult to avoid than it is worth.

The other calls come from OnVisibleChanged which is invoked _3 times_ when the tab is first removed, then reinserted, and lastly made selected by the tab drag handler. Updating the layout might be necessary if changes were made while the control was invisible, so the solution is not to remove PerformCustomLayout from OnVisibleChanged. Hacks such as setting Visible to false in OnDragDrop and true after the move is complete caused screen flashing even with SuspendDrawing set to true.
