### ISSUE TITLE
Attributes not updating, incorrect SP in training skill inferred

### ISSUE THREAD

**Issue by ab3ju** [peterhaneve/evemon#121]
After remapping a character's attributes about 12 hours ago, evemon still reports the old attributes and training rate. It also appears to be calculating the current SP in the training skill based on the time to completion and the incorrect training rate, rather than using the SP reported by ESI. Moving a skill trained to level 4, with no partial training toward level 5, into the top of the queue and updating the skill queue in evemon results in evemon showing the skill at 27% done. This results in skillplans including a scheduled remap showing a lower than actual time to completion for the currently training skill. Partially trained skills not currently training show the correct training time with incorrect current SP and SP/hour in the skill queue

**Comment by wbSD** [comment]
I think there could be more issues at play here, but the attributes not updating is a consequence of the fact that EveMon updates implants and attributes "as one".
I've described this problem before here https://github.com/peterhaneve/evemon/issues/89#issuecomment-427649097 and here https://github.com/peterhaneve/evemon/pull/13#issuecomment-403164823

The attribute issue should disappear after restarting EveMon (the next time it does an API update after that), since it then won't have the ETag stored from the Implants query, and it will then actually proceed with querying Attributes.

The other part of the problem here with the skill points/training time could maybe be related/similar to what is described on #89 - when EveMon gets mixed responses from ESI it seems to do some weird things with the skillpoint calculations. The skill queue explicitly states how long is left of a given skill, and that is heavily used in the calculation, but if for example the attributes are off then things start looking weird.
