### ISSUE TITLE
Moon reactions not fully supported

### ISSUE THREAD

**Issue by 18pd** [peterhaneve/evemon#122]
In the industry tracker reaction jobs are counted as research jobs rather than reaction jobs. Also the output descriptor for them seems to be broken. Low priority stuff I know :)

Attached image that should show both. Cheers

![evemon_1njo1gbjy5](https://user-images.githubusercontent.com/20302888/49284159-a8894500-f48b-11e8-9807-246756b379db.png)

**Comment by wbSD** [comment]
It looks like EveMon doesn't really have any support for reaction jobs yet.
The enum for industry activities does not include it, and the calculation for manufacturing jobs and researching jobs is only using the criteria "is the job a manufacturing job?" to differentiate between them.

**Comment by peterhaneve** [comment]
To really fix this fully a new category of jobs for the UI would need to be created, along with plumbing the backend to the new Reactions skill to determine how many you can actually run. It also appears that the output item being reported by ESI is broken - even if it is a different job type, I would still expect the output item field to match the output of an actual reaction (moon goo products, right?).

**Comment by wbSD** [comment]
The output item looks like it comes from the data file, I'm debugging it right now and when the Thulium Hafnite Reaction Formula blueprint is being instantiated, the value of SerializableBlueprint.ProduceItemID is 0 which is wrong, it should be 33336 (Thulium Hafnite)

**Comment by wbSD** [comment]
Yep the output item is also caused by the fact that Reactions isn't added in the code yet.
By adding Reactions to the BlueprintActivity enum, and changing the XmlGenerator Blueprints.cs to consider both Manufacturing and Reactions as activities with products, the serialized blueprint now has the correct product, and when it gets loaded into EveMon it shows the correct output product

![image](https://user-images.githubusercontent.com/1277455/49332486-dc5c8b80-f5ad-11e8-9fe7-bf8779dce627.png)

I'm gonna see if I can fix up the other places that should also be considering Reactions as an activity type, and will open a pull request.

**Comment by peterhaneve** [comment]
I am not an industrialist myself, so I am not able to test every possible in and out, but the UI has been updated to display the jobs in the right category and infer the number and range available from skills. There is still code in the blueprint browser related to the old reactions system but it does not seem to crash so it can be refactored later.
