### ISSUE TITLE
Reactions not displaying in industry tab

### ISSUE THREAD

**Issue by UAVfan** [peterhaneve/evemon#139]
When a character has active reactions in the oven, they are listed in the industry tab as "none", and the totals displayed at the bottom of the page shows "Reaction jobs remaining: 10 out of 10 max" when it should read, for example, "0 out of 10 max".

**Comment by peterhaneve** [comment]
Jobs being listed as None indicates that the blueprint activity is blank. What is likely occurring is that EVEMon was closed and reopened, but ESI is still on cooldown for industry jobs (default refresh is hourly). Therefore, the jobs get loaded from the settings cache file, which due to compatibility reasons does not retain the blueprint activity.

The issue should automatically resolve on the next ESI data refresh.
