### ISSUE TITLE
Implant Groups/Implant Sets

### ISSUE THREAD

**Issue by Paula-Myok** [peterhaneve/evemon#180]
Implant Sets  - Clones that are named and Active Clone  do not show the station they are in.

![Capture](https://user-images.githubusercontent.com/53821187/62537613-27235700-b851-11e9-95bf-b5ff9f0f4d0e.PNG)

**Comment by peterhaneve** [comment]
Unfortunately, adding the location to the clone name would break backwards compatibility, as the clone setting in the EVEMon settings file is referenced only by name, not by implant set ID. Since the user can create their own implant sets, adding the location could make the list inconsistent during settings file upgrades.
