### ISSUE TITLE
Add search function to overview

### ISSUE THREAD

**Issue by mingsan303** [peterhaneve/evemon#189]
Is it possible to add search function to overview? I think people with a lot of alts having a hard time searching for their specific character/s

**Comment by peterhaneve** [comment]
Characters can be dragged in the tab list to change their order. Sorting them may make it easier to find the desired character.

Due to EVEMon 4 crashing when exceeding more than a page or two of alts from exhausting Windows limits on the number of active controls, it is unlikely that people will be able to load enough alts to make this a severe issue.

**Comment by mingsan303** [comment]
actually i have this crashing issue ...... it keep crashing when it loading maybe because of too many alts

**Comment by peterhaneve** [comment]
EVEMon cannot include more than about 20-30 characters at once due to Windows system limits on the number of controls per application. See #54 for more information including a potential workaround.
