### ISSUE TITLE
Minor kill report issue

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#227]
In the kill reports there are some Unknown values (e.g. Triglavian ships/weapons) and a 'Type not found' image. 

Example:
![image](https://user-images.githubusercontent.com/1768983/79790378-ec643f00-834b-11ea-97b5-4a1dc628059b.png)

**Comment by wvdvegt** [comment]
Found a solution for the attacker's name:

In KillReportAttacker.UpdateContent() I changed the first line to 

`CharacterNameLabel.Text = string.IsNullOrEmpty(m_attacker.Name) || m_attacker.Name.Equals(EveMonConstants.UnknownText) ? m_attacker.ShipTypeName : m_attacker.Name;`

So for npc's it now shows the shipname instead of Unknown.

Weapons and Corporation/Alliance sometimes have a 0 typeId so can't be resolved.

**Comment by wvdvegt** [comment]
Instead of the 'Type not found' image for NPC weapons it might be better not to show one at all.

**Comment by peterhaneve** [comment]
It looks like the SDE is missing type names for these weapons. ZKillBoard appears to replicate the same image as the attacker's ship portrait in this case, but this is not possible due to how EVEMon handles the cache, as a given type ID (In this case 0) must always map to one particular image.

Showing the ship type name as the attacker might be misleading in some cases. But CCP appears to have virtually abandoned the SDE so a workaround may be required here.

**Comment by wvdvegt** [comment]
You could try to use ESI to lookup the names/types (if the ID is non-zero).

During my debugging I only encountered 0 ID values and was only able to fix the name/ship.
