### ISSUE TITLE
Books prices require correction

### ISSUE THREAD

**Issue by AnrDaemon** [peterhaneve/evemon#240]
Since recent skill prices review, many book prices are skewed by approx. 20%.

**Comment by peterhaneve** [comment]
The skill book prices are provided in the Static Data Export (SDE), so if they are incorrect it is due to CCP not updating the file.

If you could provide a complete list of the price of each skill book, it may be possible to override them manually, but it would require a fairly extensive change to the XmlGenerator.

**Comment by AnrDaemon** [comment]
Thanks for the explanation. I was expecting something like that. And I think I recall the reasoning behind this issue, now.
If my memory is right, the prices are increased consistently. I'll check it and get back to you.
