### ISSUE TITLE
Add an option to disable the new label dropdown during normal operation

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#71]
The new label to tag pilots stays annoyingly editable during normal operation. Is it possible to add an option to enable/disable the dropdown control (maybe turn it into a label when done editing)?

**Comment by peterhaneve** [comment]
Is this an issue because the edit field is stealing focus somehow?

**Comment by wvdvegt** [comment]
No focus issues but it's editable just to easy (which you do not want when the values are set) and also looks a bit odd to have an entry field at that spot. Due to the larger size it also does not align nicely with the other text.

I would have expected the actual value entry in the ESI Keys Management somewhere (like on the Characters Tab).

**Comment by peterhaneve** [comment]
The ESI Key Management window renders characters using `Graphics` drawing methods in order to avoid creating physical controls for each entry. Therefore, adding an editable component to each one would require large changes, and might slow down the window if the user has dozens of characters.

While it may look odd, the current location was the most feasible location to implement it. Perhaps having a label that turns into a combo box when clicked?

**Comment by wvdvegt** [comment]
That (turning the label temporary into a combo box when clicked) would do just fine.
