### ISSUE TITLE
Completed industry job notifications keep increasing

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#82]
Just a reminder issue:

Commit 12ae889 is a fix for completed job notifications ever increasing number when you keep EveMon running.

See issue #47 which never was fixed.

**Comment by peterhaneve** [comment]
The suggested commit does not fix the issue where it should be addressed. If the notifications are being added more than once, it means that the completed jobs are not being merged correctly.

**Comment by avianrr** [comment]
I believe I found the problem.  The jobs were stored in a list so two entries with the same jobIDs could be in the list at the same time.  I created what I hope is a fix but I have no industry going on right now to test it.  If someone can test and get back to me?
The fix is in this branch of my fork https://github.com/avianrr/evemon/tree/IndustyJobFix
Unfortunately, I forgot to branch the alpha stuff I've been working on so this ended up branched off that.

**Comment by avianrr** [comment]
> 
> 
> Think it is in essence the same solution but a more correct place to fix it (i could not find the origin).

Yea, the foreach loop in that solution was simply filtering out the duplicate entries but not preventing them.  That could have long term performance issues with large numbers of jobs. (i.e. a large corporation)
The fix I created prevents them from being added in the first place.
