### ISSUE TITLE
Alpha status skill length

### ISSUE THREAD

**Issue by mithlug** [peterhaneve/evemon#86]
It would be nice to get the time required for alpha clones on skills when in alpha state rather than always seeing the time required for omega clones.

**Comment by avianrr** [comment]
I just recently decided to start using evemon again since the ESI interface has matured enough and there seem to be some development support now.
Alpha/Omega clone state detection was not very good.  Luckily I just added some more support for that, and proper skill list display.  Hopefully it gets accepted!
I'm planning on doing some more work on alpha state support so keep an eye out.
