### ISSUE TITLE
SP/Hour incorrect when using accelerators

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#90]
Related to #89, the SP/Hour is also incorrect as it uses the momentary GetBaseSPPerHour (which will drop once the accelerator is depleted).

The calculation is done in Skills.cs line 293:

`public int SkillPointsPerHour => (int)Math.Round(Character?.GetBaseSPPerHour(this) ?? 0);`

I think better would be to use the remaining time and remaining SP but I'm not sure that last value is updated in EveEsi (I think it only reflects the SP trained when you re-order the queue so training is paused for a skill).

**Comment by peterhaneve** [comment]
There is no way to know if an accelerator is active as there is no endpoint to tell when it expires. The SP/hour is also used in locations like the skill planner to determine how long a hypothetical queue would take.

Since accelerators can apply for varying amounts, along with items such as new player implants, there is no good way to count these out.
